#!/bin/bash 

# change dir for temporary file useage
cd /tmp

website='http://www.vpnbook.com'
webpage="$website/freevpn"
vpn_file='vpns.html'


# download html
wget -q -nv -O $vpn_file $webpage

vpns=$(xmllint --html --xpath \
  '(//ul[contains(@class,"disc")])[2]//li/a/@href' \
  $vpn_file 2>/dev/null | sed -e 's/href=//g;s/\"//g')

urls=($vpns)

options=("EUROPE1" "EUROPE2" "USA1" "USA2" "CANADA" "GERMANY" "QUIT")

choose_vpn(){
  local vpns=($(ls *.ovpn) "EXIT")
  select vpn in "${vpns[@]}"
  do
    case $vpn in
      *.ovpn)
        sudo openvpn $vpn
      ;;
      "EXIT") 
        echo "Exiting program..."
        exit
      ;;
      *)
        echo "Invalid input" >&2
        exit 1
        
  esac
done

}

download_and_unzip(){

  index=$1
  file_name=$2
  wget -q -nv -O $file_name $website${urls[$index]} && unzip -qq -u $file_name
  rm -rf $file_name

}

username=$(xmllint --html --xpath '(//li[contains(text(),"Username")])[2]/strong/text()' \
 $vpn_file 2>/dev/null)

password=$(xmllint --html --xpath \
  '(//li[contains(text(),"Password")])[2]/strong/text()' $vpn_file 2>/dev/null)


cat << EOF
USE THESE CREDENTIALS

Username: ${username}
Password: ${password}

EOF


select opt in "${options[@]}"
do
  case $opt in 
    "EUROPE1")
      zip_name="${opt}.zip"
      mkdir -p $opt 
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 0 $zip_name
      choose_vpn
      break
    ;;
    "EUROPE2")
      zip_name="${opt}.zip"
      mkdir -p $opt 
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 1 $zip_name
      choose_vpn
      break
    ;;
    "USA1")
      zip_name="${opt}.zip"
      mkdir -p $opt 
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 2 $zip_name
      choose_vpn
      break
    ;;
    "USA2")
      zip_name="${opt}.zip"
      mkdir -p $opt 
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 3 $zip_name
      choose_vpn
      break
    ;;
    "CANADA")
      zip_name="${opt}.zip"
      mkdir -p $opt
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 4 $zip_name
      choose_vpn
      break
    ;;
    "GERMANY")
      zip_name="${opt}.zip"
      mkdir -p $opt 
      cd $opt
      echo -e "Connecting to the ${opt} server"
      download_and_unzip 5 $zip_name
      choose_vpn
      break
    ;;
    "QUIT")
      echo "Exiting program..."
      exit
    ;;
    *)
      echo "Invalid input" >&2
      exit 1
    esac
done
