#!/bin/bash 

readonly WEBSITE='http://www.vpnbook.com'
readonly WEBPAGE="$WEBSITE/freevpn"
readonly VPN_FILE='/tmp/vpns.html'
readonly OPTIONS=("EUROPE1" "EUROPE2" "USA1" "USA2" "CANADA" "GERMANY" "CREDS" "QUIT")
readonly PS3="Select a number (enter for options):"



# function to download, unzip and remove zip folder
download_and_unzip(){

  local index=$1
  local file_name=$2
  wget -q -nv -O $file_name $WEBSITE${vpns[$index]} && unzip -qq -u $file_name
  rm -rf $file_name

}


# function to choose the extracted vpns in the folder
choose_vpn(){

  local vpns=($(ls *.ovpn) "CREDS" "EXIT" "BACK")

  select vpn in "${vpns[@]}"
  do
    case $vpn in
      *.ovpn)
        clear
        sudo openvpn $vpn
      ;;
      "CREDS")
        clear
        get_creds
      ;;
      "EXIT") 
        clear
        echo "Exiting program..."
        exit
      ;;
      "BACK")
        clear
        break
      ;;
      *)
        clear
        echo "Invalid input" >&2
        exit 1
  esac
done

}
# move to temporary directory for temp file usage
temp_dir(){

cd /tmp

}

# download html from vpn book
download_html(){

wget -q -nv -O $VPN_FILE $WEBPAGE

}

# get the credentials to use the vpn
get_creds(){

  # xpath to extract the username
  local username=$(xmllint --html --xpath \
            '(//li[contains(text(),"Username")])[2]/strong/text()' \
             $VPN_FILE 2>/dev/null)
  # xpath to extract the password
  local password=$(xmllint --html --xpath \
            '(//li[contains(text(),"Password")])[2]/strong/text()' \
             $VPN_FILE 2>/dev/null)

  # here document to show creds
  cat <<- EOF



  ######USE THESE CREDENTIALS######
  Username: ${username}
  Password: ${password}
  ######USE THESE CREDENTIALS######



EOF

}


# function to extract the vpn download urls
get_vpns(){
  
  # xpath to populate the VPNS variable with an array of the download links to the vpns
  vpns=($(xmllint --html --xpath \
          '(//ul[contains(@class,"disc")])[2]//li/a/@href' \
          $VPN_FILE 2>/dev/null \
          | sed -e 's/href=//g;s/\"//g'))

}


# function to select the VPN server location
select_location(){
  local zip_name=

  select opt in "${OPTIONS[@]}"
  do
    case $opt in 
      "EUROPE1")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt 
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 0 $zip_name
        choose_vpn
        clear
      ;;
      "EUROPE2")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt 
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 1 $zip_name
        choose_vpn
      ;;
      "USA1")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt 
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 2 $zip_name
        choose_vpn
      ;;
      "USA2")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt 
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 3 $zip_name
        choose_vpn
      ;;
      "CANADA")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 4 $zip_name
        choose_vpn
      ;;
      "GERMANY")
        clear
        zip_name="${opt}.zip"
        mkdir -p $opt 
        cd $opt
        echo -e "Connecting to the ${opt} server"
        download_and_unzip 5 $zip_name
        choose_vpn
      ;;
      "CREDS")
        clear
        get_creds
      ;;
      "QUIT")
        clear
        echo "Exiting program..."
        exit
      ;;
      *)
        clear
        echo "Invalid input" >&2
        exit 1
      esac
  done

}


main(){

  temp_dir
  download_html
  get_creds
  get_vpns
  select_location

}
main
