#! /usr/bin/env bash

# changer dir for temporary file useage
cd /tmp

website='http://www.vpnbook.com'
webpage="$website/freevpn"
vpn_file='vpns.html'

choose_vpn(){
  local vpns=($(ls) "EXIT")
  select vpn in "${vpns[@]}"
  do
    case $vpn in
      *.ovpn)
        sudo openvpn $vpn
      ;;
      "EXIT") 
        echo "Exiting program..."
        exit
      ;;
      *)
        echo "Invalid input" >&2
        exit 1
        
  esac
done

}

# download html
wget -q -nv -O $vpn_file $webpage

username=$(xmllint --html --xpath '(//li[contains(text(),"Username")])[2]/strong/text()' \
 $vpn_file 2>/dev/null )

password=$(xmllint --html --xpath \
  '(//li[contains(text(),"Password")])[2]/strong/text()' $vpn_file 2>/dev/null )

cat << EOF
USE THESE CREDENTIALS

Username: ${username}
Password: ${password}

EOF

vpns=$(xmllint --html --xpath \
  '(//ul[contains(@class,"disc")])[2]//li/a/@href' \
  $vpn_file 2>/dev/null | sed s/href=//g | sed s/\"//g  )

urls=($vpns)

options=("EUROPE1" "EUROPE2" "USA1" "USA2" "CANADA" "GERMANY" "QUIT")

select opt in "${options[@]}"
do
  case $opt in 
    "EUROPE1")
      dirname="EUROPE1"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the EUROPE1 server"
      curl -s $website${urls[0]} | bsdtar xf - -C $dirname
      cd EUROPE1/
      choose_vpn
      break
    ;;
    "EUROPE2")
      dirname="EUROPE2"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the EUROPE2 server"
      curl -s $website${urls[1]} | bsdtar xf - -C $dirname
      cd $dirname 
      choose_vpn
      break
    ;;
    "USA1")
      dirname="USA1"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the USA1 server"
      curl -s $website${urls[2]} | bsdtar xf - -C $dirname
      cd $dirname 
      choose_vpn
      break
    ;;
    "USA2")
      dirname="USA2"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the USA2 server"
      curl -s $website${urls[3]} | bsdtar xf - -C $dirname
      cd $dirname
      choose_vpn
      break
    ;;
    "CANADA")
      dirname="CANADA"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the CANADA server"
      curl -s $website${urls[4]} | bsdtar xf - -C $dirname
      cd $dirname
      choose_vpn
      break
    ;;
    "GERMANY")
      dirname="GERMANY"
      mkdir -p $dirname 2>/dev/null
      echo -e "Connecting to the GERMANY server"
      curl -s $website${urls[5]} | bsdtar xf - -C $dirname
      cd $dirname 
      choose_vpn
      break
    ;;
    "QUIT")
      echo "Exiting program..."
      exit
    ;;
    *)
      echo "Invalid input" >&2
      exit 1
    esac
done
